In [7]:
#PYTHON FOR DATA ANALYSIS

In [11]:
import numpy as np

In [13]:
mylist = [1,2,3,4]

In [15]:
myarray = np.array(mylist)

In [17]:
myarray

array([1, 2, 3, 4])

In [19]:
mylist2 = [5,6,7,8]

In [21]:
mylists = [mylist,mylist2]

In [23]:
mylists

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [25]:
myarray2 = np.array(mylists)

In [27]:
myarray2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
myarray2.shape

(2, 4)

In [31]:
myarray.dtype

dtype('int64')

In [33]:
myzeros = np.zeros(5)

In [35]:
myzeros.dtype

dtype('float64')

In [37]:
np.empty(5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [43]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [45]:
5/2

2.5

In [47]:
array = np.array([[1,2,3,4],[8,9,10,11]])

In [49]:
array

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [51]:
array * array

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [53]:
array - array

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [55]:
1 / array

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [57]:
array ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [59]:
#indexing arrays

In [61]:
import numpy as np

In [65]:
arr = np.arange(0,11)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [87]:
arr[0:5] = 100

In [89]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [93]:
slicearr = arr[0:6]

In [95]:
slicearr

array([100, 100, 100, 100, 100,   5])

In [97]:
slicearr[0:5] = 99

In [99]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [103]:
# In Numpy there is only one-copy of the array and changing a slice of the array will also effect the orignal array

In [105]:
# To avoid this we have to exclusively create a copy of the array and make changes to it

In [107]:
arr_copy = arr.copy()

In [120]:
arr_copy = slicearr

In [124]:
arr_copy[0:6]=  98

In [126]:
arr

array([98, 98, 98, 98, 98, 98,  6,  7,  8,  9, 10])

In [128]:
slicearr

array([98, 98, 98, 98, 98, 98])

In [130]:
arr_copy


array([98, 98, 98, 98, 98, 98])

In [134]:
arr2d = np.array(([1,2,3],[5,6,7],[8,9,10]))

arr2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [140]:
arr_2d[1][0] 
# array[row][col]

5

In [ ]:
arr2d[